import boto3
from botocore.client import BaseClient

# session is picked up from the ~/.aws/credentials file

# Uncomment for TR session generated by cloud-tool
boto3.setup_default_session(profile_name='cloud-tool-default')
session = boto3.session.Session(profile_name='cloud-tool-default')

#print("\nEC2:")
#ec2_client = session.client('ec2', region_name='eu-west-1')
#ec2_response = ec2_client.describe_instances()
##print(ec2_response)
#for reservation in ec2_response["Reservations"]:
#    for instance in reservation["Instances"]:
#        print(instance)
#        print(instance["InstanceId"])


print("\nRDS:")
rds_client = session.client('rds', region_name='eu-west-1')
rds_response = rds_client.describe_db_instances()
print(rds_response)
print("\n")
for db_instance in rds_response["DBInstances"]:
        print(db_instance["DBInstanceIdentifier"])
        print(db_instance["Engine"])
        print(db_instance["PubliclyAccessible"])


#print("\nS3:")
#s3_client = session.client('s3')
#s3_resource = boto3.resource('s3')
#for bucket in s3_resource.buckets.all():
#    acl = bucket.Acl()
#    print(acl)

